### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by spectraldoy** [Szplugz/neelkhare.com#1]
Hello I want to use your website but it isn't working. This is obviously very poorly designed. I don't understand why you would write something like this

<img width="775" alt="image" src="https://user-images.githubusercontent.com/41366802/169488803-99b54a31-66e4-4b0d-8993-b7dd55a370f2.png">

**Comment by Szplugz** [comment]
You nutjob, I haven't purchased a domain yet. Use yarn start or npm run start. Also there's not much on it yet I just finished the left side of the landing page yesterday



On May 20, 2022 at 03:36, <Aditya ***@***.***>> wrote:


Hello I want to use your website but it isn't working. This is obviously very poorly designed

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/41366802/169488803-99b54a31-66e4-4b0d-8993-b7dd55a370f2.png__;!!DZ3fjg!_ZyN5JCsi8ulLYIOEdKYENUF1bhVosNVWdkQXN_WrPAfP9qqVmYlr2URMRdhHB3hvS0sENPSeyJ6Gir4NxN6iNetobc$>

**Comment by Szplugz** [comment]
closed because no

**Comment by spectraldoy** [comment]
It still doesn't work

![Screenshot_20220520-133327](https://user-images.githubusercontent.com/41366802/169606477-75520cbe-06ad-42c6-8e14-f5c694683230.jpg)
